ports_global = [
{'name': 'Durres (Durazzo)', 'key': 'Port of Durres (Durazzo) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Durr%C3%ABs'} ,
{'name': 'Sarande', 'key': 'Port of Sarande wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Sarand%C3%AB'} ,
{'name': 'Shengjjin', 'key': 'Port of Shengjjin wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Sh%C3%ABngjin'} ,
{'name': 'Vlore (Vlora, Vlone)', 'key': 'Port of Vlore (Vlora, Vlone) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Vlor%C3%AB'} ,
{'name': 'Algiers', 'key': 'Port of Algiers wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Wahran'} ,
{'name': 'Annaba (Ex Bone)', 'key': 'Port of Annaba (Ex Bone) wikipedia', 'wiki': None} ,
{'name': 'Arzew', 'key': 'Port of Arzew wikipedia', 'wiki': None} ,
{'name': 'Bejaia (Ex Bougie)', 'key': 'Port of Bejaia (Ex Bougie) wikipedia', 'wiki': None} ,
{'name': 'Dellys', 'key': 'Port of Dellys wikipedia', 'wiki': None} ,
{'name': 'Ghazaouet', 'key': 'Port of Ghazaouet wikipedia', 'wiki': None} ,
{'name': 'Mostaganem', 'key': 'Port of Mostaganem wikipedia', 'wiki': None} ,
{'name': 'Oran', 'key': 'Port of Oran wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Wahran'} ,
{'name': 'Skikda (Ex Philippeville)', 'key': 'Port of Skikda (Ex Philippeville) wikipedia', 'wiki': None} ,
{'name': 'Tenes', 'key': 'Port of Tenes wikipedia', 'wiki': None} ,
{'name': 'Pago Pago', 'key': 'Port of Pago Pago wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Pago_Pago_Harbor'} ,
{'name': 'Cabinda', 'key': 'Port of Cabinda wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Namibe'} ,
{'name': 'Lobito', 'key': 'Port of Lobito wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Lobito'} ,
{'name': 'Luanda', 'key': 'Port of Luanda wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Luanda'} ,
{'name': 'Namibe', 'key': 'Port of Namibe wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Namibe'} ,
{'name': 'Porto Amboim', 'key': 'Port of Porto Amboim wikipedia', 'wiki': None} ,
{'name': 'Soyo', 'key': 'Port of Soyo wikipedia', 'wiki': None} ,
{'name': 'Bahia Blanca', 'key': 'Port of Bahia Blanca wikipedia', 'wiki': None} ,
{'name': 'Buenos Aires', 'key': 'Port of Buenos Aires wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Buenos_Aires'} ,
{'name': 'Comodoro Rivadavia', 'key': 'Port of Comodoro Rivadavia wikipedia', 'wiki': None} ,
{'name': 'Concepcion del Uruguay', 'key': 'Port of Concepcion del Uruguay wikipedia', 'wiki': None} ,
{'name': 'Mar del Plata', 'key': 'Port of Mar del Plata wikipedia', 'wiki': None} ,
{'name': 'Necochea', 'key': 'Port of Necochea wikipedia', 'wiki': None} ,
{'name': 'Puerto Madryn', 'key': 'Port of Puerto Madryn wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Madryn'} ,
{'name': 'Rio Gallegos', 'key': 'Port of Rio Gallegos wikipedia', 'wiki': None} ,
{'name': 'Rosario', 'key': 'Port of Rosario wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rosario'} ,
{'name': 'Santa Fe', 'key': 'Port of Santa Fe wikipedia', 'wiki': None} ,
{'name': 'Ushuaia', 'key': 'Port of Ushuaia wikipedia', 'wiki': None} ,
{'name': 'Oranjestad', 'key': 'Port of Oranjestad wikipedia', 'wiki': None} ,
{'name': 'Georgetown', 'key': 'Port of Georgetown wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Penang'} ,
{'name': 'Adelaide', 'key': 'Port of Adelaide wikipedia', 'wiki': None} ,
{'name': 'Brisbane', 'key': 'Port of Brisbane wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Brisbane'} ,
{'name': 'Cairns', 'key': 'Port of Cairns wikipedia', 'wiki': None} ,
{'name': 'Darwin', 'key': 'Port of Darwin wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Darwin_Harbour'} ,
{'name': 'Devonport', 'key': 'Port of Devonport wikipedia', 'wiki': None} ,
{'name': 'Fremantle', 'key': 'Port of Fremantle wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Fremantle_Harbour'} ,
{'name': 'Geelong', 'key': 'Port of Geelong wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Geelong'} ,
{'name': 'Hobart', 'key': 'Port of Hobart wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hobart'} ,
{'name': 'Mackay', 'key': 'Port of Mackay wikipedia', 'wiki': None} ,
{'name': 'Melbourne', 'key': 'Port of Melbourne wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Melbourne'} ,
{'name': 'Sydney', 'key': 'Port of Sydney wikipedia', 'wiki': None} ,
{'name': 'Townsville', 'key': 'Port of Townsville wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Townsville'} ,
{'name': 'Baku', 'key': 'Port of Baku wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Baku'} ,
{'name': 'Freeport', 'key': 'Port of Freeport wikipedia', 'wiki': None} ,
{'name': 'Nassau', 'key': 'Port of Nassau wikipedia', 'wiki': None} ,
{'name': 'Mina Salman', 'key': 'Port of Mina Salman wikipedia', 'wiki': None} ,
{'name': 'Sitra', 'key': 'Port of Sitra wikipedia', 'wiki': None} ,
{'name': 'Chittagong', 'key': 'Port of Chittagong wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Chittagong'} ,
{'name': 'Mongla', 'key': 'Port of Mongla wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Mongla'} ,
{'name': 'Bridgetown', 'key': 'Port of Bridgetown wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Bridgetown'} ,
{'name': 'Antwerp', 'key': 'Port of Antwerp wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Antwerp'} ,
{'name': 'Brussels (Bruxelles)', 'key': 'Port of Brussels (Bruxelles) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Brussels'} ,
{'name': 'Ghent', 'key': 'Port of Ghent wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ghent'} ,
{'name': 'Liege', 'key': 'Port of Liege wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Li%C3%A8ge'} ,
{'name': 'Zeebrugge', 'key': 'Port of Zeebrugge wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Zeebrugge'} ,
{'name': 'Belize City', 'key': 'Port of Belize City wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Belize'} ,
{'name': 'Cotonou', 'key': 'Port of Cotonou wikipedia', 'wiki': None} ,
{'name': 'Hamilton', 'key': 'Port of Hamilton wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Hamilton_Harbour'} ,
{'name': 'St Georges', 'key': 'Port of St Georges wikipedia', 'wiki': None} ,
{'name': 'Belem', 'key': 'Port of Belem wikipedia', 'wiki': None} ,
{'name': 'Fortaleza', 'key': 'Port of Fortaleza wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Pecem'} ,
{'name': 'Imbituba', 'key': 'Port of Imbituba wikipedia', 'wiki': None} ,
{'name': 'Manaus', 'key': 'Port of Manaus wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Manaus'} ,
{'name': 'Paranagua', 'key': 'Port of Paranagua wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Paranagu%C3%A1'} ,
{'name': 'Porto Alegre', 'key': 'Port of Porto Alegre wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Porto_Alegre'} ,
{'name': 'Recife', 'key': 'Port of Recife wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Recife_Port'} ,
{'name': 'Rio De Janeiro', 'key': 'Port of Rio De Janeiro wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rio_de_Janeiro'} ,
{'name': 'Rio Grande', 'key': 'Port of Rio Grande wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rio_Grande'} ,
{'name': 'Salvador', 'key': 'Port of Salvador wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Salvador'} ,
{'name': 'Santos', 'key': 'Port of Santos wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Santos'} ,
{'name': 'Vitoria', 'key': 'Port of Vitoria wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Victoria'} ,
{'name': 'Kuala Belait', 'key': 'Port of Kuala Belait wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Kuala_Belait_Port'} ,
{'name': 'Muara', 'key': 'Port of Muara wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Muara_Port'} ,
{'name': 'Varna', 'key': 'Port of Varna wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Varna'} ,
{'name': 'Kompongsom', 'key': 'Port of Kompongsom wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Sihanoukville_Autonomous_Port'} ,
{'name': 'Phnom Penh', 'key': 'Port of Phnom Penh wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Sihanoukville_Autonomous_Port'} ,
{'name': 'Douala', 'key': 'Port of Douala wikipedia', 'wiki': None} ,
{'name': 'Kribi', 'key': 'Port of Kribi wikipedia', 'wiki': None} ,
{'name': 'Tiko', 'key': 'Port of Tiko wikipedia', 'wiki': None} ,
{'name': 'Alberni', 'key': 'Port of Alberni wikipedia', 'wiki': None} ,
{'name': 'Becancour', 'key': 'Port of Becancour wikipedia', 'wiki': None} ,
{'name': 'Churchill', 'key': 'Port of Churchill wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Churchill'} ,
{'name': 'Fraser River Port (Port of New Westminster)', 'key': 'Port of Fraser River Port (Port of New Westminster) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Vancouver'} ,
{'name': 'Halifax', 'key': 'Port of Halifax wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Halifax'} ,
{'name': 'Hamilton', 'key': 'Port of Hamilton wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Hamilton_Harbour'} ,
{'name': 'Halifax', 'key': 'Port of Halifax wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Halifax'} ,
{'name': 'Montreal', 'key': 'Port of Montreal wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Montreal'} ,
{'name': 'Nanaimo', 'key': 'Port of Nanaimo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Nanaimo_Harbour'} ,
{'name': 'Saguenay', 'key': 'Port of Saguenay wikipedia', 'wiki': None} ,
{'name': 'Sept Iles (Seven Islands)', 'key': 'Port of Sept Iles (Seven Islands) wikipedia', 'wiki': None} ,
{'name': 'St Johns', 'key': 'Port of St Johns wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Saint_John'} ,
{'name': 'Sydney', 'key': 'Port of Sydney wikipedia', 'wiki': None} ,
{'name': 'Thunder Bay', 'key': 'Port of Thunder Bay wikipedia', 'wiki': None} ,
{'name': 'Toronto', 'key': 'Port of Toronto wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Toronto'} ,
{'name': 'Trois-Rivieres', 'key': 'Port of Trois-Rivieres wikipedia', 'wiki': None} ,
{'name': 'Vancouver', 'key': 'Port of Vancouver wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Vancouver'} ,
{'name': 'Windsor', 'key': 'Port of Windsor wikipedia', 'wiki': None} ,
{'name': 'Las Palmas', 'key': 'Port of Las Palmas wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Las_Palmas'} ,
{'name': 'Santa Cruz de Tenerife', 'key': 'Port of Santa Cruz de Tenerife wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Santa_Cruz_de_Tenerife'} ,
{'name': 'Porto Grande', 'key': 'Port of Porto Grande wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rio_Grande'} ,
{'name': 'Georgetown, Grand Cayman', 'key': 'Port of Georgetown, Grand Cayman wikipedia', 'wiki': None} ,
{'name': 'Antofagasta', 'key': 'Port of Antofagasta wikipedia', 'wiki': None} ,
{'name': 'Arica', 'key': 'Port of Arica wikipedia', 'wiki': None} ,
{'name': 'Chanaral', 'key': 'Port of Chanaral wikipedia', 'wiki': None} ,
{'name': 'Iquique', 'key': 'Port of Iquique wikipedia', 'wiki': None} ,
{'name': 'Puerto Montt', 'key': 'Port of Puerto Montt wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Montt'} ,
{'name': 'Punta Arenas', 'key': 'Port of Punta Arenas wikipedia', 'wiki': None} ,
{'name': 'San Antonio', 'key': 'Port of San Antonio wikipedia', 'wiki': None} ,
{'name': 'San Vicente', 'key': 'Port of San Vicente wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_de_San_Vicente'} ,
{'name': 'Talcahuano', 'key': 'Port of Talcahuano wikipedia', 'wiki': None} ,
{'name': 'Valparaiso', 'key': 'Port of Valparaiso wikipedia', 'wiki': None} ,
{'name': 'Dalian', 'key': 'Port of Dalian wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Dalian'} ,
{'name': 'Fuzhou', 'key': 'Port of Fuzhou wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Fuzhou'} ,
{'name': 'Guangzhou', 'key': 'Port of Guangzhou wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Guangzhou'} ,
{'name': 'Haikou', 'key': 'Port of Haikou wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Haikou_New_Port'} ,
{'name': 'Lianyungang', 'key': 'Port of Lianyungang wikipedia', 'wiki': None} ,
{'name': 'Nantong', 'key': 'Port of Nantong wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Nantong'} ,
{'name': 'Ningbo', 'key': 'Port of Ningbo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ningbo-Zhoushan'} ,
{'name': 'Qingdao', 'key': 'Port of Qingdao wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Qingdao_Port'} ,
{'name': 'Qinhuangdao', 'key': 'Port of Qinhuangdao wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Qinhuangdao_Port'} ,
{'name': 'Shanghai', 'key': 'Port of Shanghai wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Shanghai'} ,
{'name': 'Shantou', 'key': 'Port of Shantou wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Shantou'} ,
{'name': 'Tianjin', 'key': 'Port of Tianjin wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tianjin'} ,
{'name': 'Xiamen', 'key': 'Port of Xiamen wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Xiamen'} ,
{'name': 'Zhanjiang', 'key': 'Port of Zhanjiang wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Zhanjiang'} ,
{'name': 'Barranquilla', 'key': 'Port of Barranquilla wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Colombia'} ,
{'name': 'Buenaventura', 'key': 'Port of Buenaventura wikipedia', 'wiki': None} ,
{'name': 'Cartagena', 'key': 'Port of Cartagena wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cartagena'} ,
{'name': 'Puerto Bolivar', 'key': 'Port of Puerto Bolivar wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Bol%C3%ADvar'} ,
{'name': 'Tumaco', 'key': 'Port of Tumaco wikipedia', 'wiki': None} ,
{'name': 'Turbo', 'key': 'Port of Turbo wikipedia', 'wiki': None} ,
{'name': 'Moroni', 'key': 'Port of Moroni wikipedia', 'wiki': None} ,
{'name': 'Mutsamudu', 'key': 'Port of Mutsamudu wikipedia', 'wiki': None} ,
{'name': 'Pointe Noire', 'key': 'Port of Pointe Noire wikipedia', 'wiki': None} ,
{'name': 'Banana', 'key': 'Port of Banana wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Bol%C3%ADvar'} ,
{'name': 'Boma', 'key': 'Port of Boma wikipedia', 'wiki': None} ,
{'name': 'Caldera', 'key': 'Port of Caldera wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Caldera_Port'} ,
{'name': 'Golfito', 'key': 'Port of Golfito wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Jim%C3%A9nez'} ,
{'name': 'Puntarenas', 'key': 'Port of Puntarenas wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Caldera_Port'} ,
{'name': 'Quepos', 'key': 'Port of Quepos wikipedia', 'wiki': None} ,
{'name': 'Abidjan', 'key': 'Port of Abidjan wikipedia', 'wiki': None} ,
{'name': 'Rijeka Bakar', 'key': 'Port of Rijeka Bakar wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rijeka'} ,
{'name': 'Zadar', 'key': 'Port of Zadar wikipedia', 'wiki': None} ,
{'name': 'Dubrovnik', 'key': 'Port of Dubrovnik wikipedia', 'wiki': None} ,
{'name': 'Omisalj', 'key': 'Port of Omisalj wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rijeka'} ,
{'name': 'Ploce', 'key': 'Port of Ploce wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Plo%C4%8De'} ,
{'name': 'Pula', 'key': 'Port of Pula wikipedia', 'wiki': None} ,
{'name': 'Sibenik', 'key': 'Port of Sibenik wikipedia', 'wiki': None} ,
{'name': 'Split', 'key': 'Port of Split wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Split'} ,
{'name': 'Havana', 'key': 'Port of Havana wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Havana_Harbor'} ,
{'name': 'Manzanillo', 'key': 'Port of Manzanillo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Manzanillo'} ,
{'name': 'Matanzas', 'key': 'Port of Matanzas wikipedia', 'wiki': None} ,
{'name': 'Nuevitas', 'key': 'Port of Nuevitas wikipedia', 'wiki': None} ,
{'name': 'Santiago de Cuba', 'key': 'Port of Santiago de Cuba wikipedia', 'wiki': None} ,
{'name': 'Akrotiri', 'key': 'Port of Akrotiri wikipedia', 'wiki': None} ,
{'name': 'Famagusta', 'key': 'Port of Famagusta wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Famagusta'} ,
{'name': 'Larnaca', 'key': 'Port of Larnaca wikipedia', 'wiki': None} ,
{'name': 'Limassol', 'key': 'Port of Limassol wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Limassol'} ,
{'name': 'Paphos', 'key': 'Port of Paphos wikipedia', 'wiki': None} ,
{'name': 'Vassiliko', 'key': 'Port of Vassiliko wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Limassol'} ,
{'name': 'Aarhus', 'key': 'Port of Aarhus wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Aarhus'} ,
{'name': 'Esbjerg', 'key': 'Port of Esbjerg wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Esbjerg'} ,
{'name': 'Fredericia', 'key': 'Port of Fredericia wikipedia', 'wiki': None} ,
{'name': 'Frederikshavn', 'key': 'Port of Frederikshavn wikipedia', 'wiki': None} ,
{'name': 'Grenaa', 'key': 'Port of Grenaa wikipedia', 'wiki': None} ,
{'name': 'Odense', 'key': 'Port of Odense wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Odense'} ,
{'name': 'Ronne', 'key': 'Port of Ronne wikipedia', 'wiki': None} ,
{'name': 'Djibouti', 'key': 'Port of Djibouti wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Djibouti'} ,
{'name': 'Portsmouth', 'key': 'Port of Portsmouth wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Portsmouth_International_Port'} ,
{'name': 'Roseau', 'key': 'Port of Roseau wikipedia', 'wiki': None} ,
{'name': 'Barahona', 'key': 'Port of Barahona wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Barahona'} ,
{'name': 'La Romana', 'key': 'Port of La Romana wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Central_Romana_Port'} ,
{'name': 'Puerto Plata', 'key': 'Port of Puerto Plata wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Puerto_Plata'} ,
{'name': 'Rio Haina', 'key': 'Port of Rio Haina wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Haina_Occidental_Port'} ,
{'name': 'San Pedro de Macoris', 'key': 'Port of San Pedro de Macoris wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_San_Pedro_de_Macoris'} ,
{'name': 'Santo Domingo', 'key': 'Port of Santo Domingo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Santo_Domingo'} ,
{'name': 'Esmeraldas', 'key': 'Port of Esmeraldas wikipedia', 'wiki': None} ,
{'name': 'Guayaquil', 'key': 'Port of Guayaquil wikipedia', 'wiki': None} ,
{'name': 'La Libertad', 'key': 'Port of La Libertad wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Libertad,_Sonora'} ,
{'name': 'Manta', 'key': 'Port of Manta wikipedia', 'wiki': None} ,
{'name': 'Puerto Bolivar', 'key': 'Port of Puerto Bolivar wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Bol%C3%ADvar'} ,
{'name': 'San Lorenzo', 'key': 'Port of San Lorenzo wikipedia', 'wiki': None} ,
{'name': 'Alexandria', 'key': 'Port of Alexandria wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Alexandria_Port'} ,
{'name': 'Damietta', 'key': 'Port of Damietta wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Damietta_Port'} ,
{'name': 'Port Said', 'key': 'Port of Port Said wikipedia', 'wiki': None} ,
{'name': 'Suez (Al Suweis)', 'key': 'Port of Suez (Al Suweis) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Suez_Port'} ,
{'name': 'Acajutla', 'key': 'Port of Acajutla wikipedia', 'wiki': None} ,
{'name': 'Cutuco', 'key': 'Port of Cutuco wikipedia', 'wiki': None} ,
{'name': 'Bata', 'key': 'Port of Bata wikipedia', 'wiki': None} ,
{'name': 'Ceiba Marine Terminal', 'key': 'Port of Ceiba Marine Terminal wikipedia', 'wiki': None} ,
{'name': 'Malabo (Rey Malabo)', 'key': 'Port of Malabo (Rey Malabo) wikipedia', 'wiki': None} ,
{'name': 'Pärnu', 'key': 'Port of Pärnu wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_P%C3%A4rnu'} ,
{'name': 'Tallinn', 'key': 'Port of Tallinn wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tallinn'} ,
{'name': 'Klaksvik', 'key': 'Port of Klaksvik wikipedia', 'wiki': None} ,
{'name': 'Torshavn', 'key': 'Port of Torshavn wikipedia', 'wiki': None} ,
{'name': 'Labasa (Lambasa)', 'key': 'Port of Labasa (Lambasa) wikipedia', 'wiki': None} ,
{'name': 'Lautoka', 'key': 'Port of Lautoka wikipedia', 'wiki': None} ,
{'name': 'Levuka', 'key': 'Port of Levuka wikipedia', 'wiki': None} ,
{'name': 'Savu Savu', 'key': 'Port of Savu Savu wikipedia', 'wiki': None} ,
{'name': 'Suva', 'key': 'Port of Suva wikipedia', 'wiki': None} ,
{'name': 'Hamina', 'key': 'Port of Hamina wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hamina-Kotka'} ,
{'name': 'Helsinki', 'key': 'Port of Helsinki wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Helsinki'} ,
{'name': 'Kokkola', 'key': 'Port of Kokkola wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Kokkola'} ,
{'name': 'Kotka', 'key': 'Port of Kotka wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hamina-Kotka'} ,
{'name': 'Loviisa', 'key': 'Port of Loviisa wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Loviisa'} ,
{'name': 'Oulu', 'key': 'Port of Oulu wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Oulu'} ,
{'name': 'Pori', 'key': 'Port of Pori wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Pori'} ,
{'name': 'Rauma', 'key': 'Port of Rauma wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rauma'} ,
{'name': 'Turku', 'key': 'Port of Turku wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Turku'} ,
{'name': 'Uusikaupunki', 'key': 'Port of Uusikaupunki wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Uusikaupunki'} ,
{'name': 'Vaasa', 'key': 'Port of Vaasa wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Vaasa'} ,
{'name': 'Bordeaux', 'key': 'Port of Bordeaux wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Bordeaux_Harbour'} ,
{'name': 'Boulogne Sur Mer', 'key': 'Port of Boulogne Sur Mer wikipedia', 'wiki': None} ,
{'name': 'Cherbourg', 'key': 'Port of Cherbourg wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Cherbourg_Harbour'} ,
{'name': 'Dunkerque', 'key': 'Port of Dunkerque wikipedia', 'wiki': None} ,
{'name': 'La Rochelle-Pallice', 'key': 'Port of La Rochelle-Pallice wikipedia', 'wiki': None} ,
{'name': 'Le Havre', 'key': 'Port of Le Havre wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Le_Havre'} ,
{'name': 'Marseille', 'key': 'Port of Marseille wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Marseille-Fos_Port'} ,
{'name': 'Nantes-St. Nazaire', 'key': 'Port of Nantes-St. Nazaire wikipedia', 'wiki': None} ,
{'name': 'Paris', 'key': 'Port of Paris wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Le_Havre'} ,
{'name': 'Rouen', 'key': 'Port of Rouen wikipedia', 'wiki': None} ,
{'name': 'St Malo', 'key': 'Port of St Malo wikipedia', 'wiki': None} ,
{'name': 'Strasbourg', 'key': 'Port of Strasbourg wikipedia', 'wiki': None} ,
{'name': 'Toulon', 'key': 'Port of Toulon wikipedia', 'wiki': None} ,
{'name': 'Cayenne', 'key': 'Port of Cayenne wikipedia', 'wiki': None} ,
{'name': 'Papeete', 'key': 'Port of Papeete wikipedia', 'wiki': None} ,
{'name': 'Cap Lopez', 'key': 'Port of Cap Lopez wikipedia', 'wiki': None} ,
{'name': 'Libreville', 'key': 'Port of Libreville wikipedia', 'wiki': None} ,
{'name': 'Owendo', 'key': 'Port of Owendo wikipedia', 'wiki': None} ,
{'name': 'Port Gentil', 'key': 'Port of Port Gentil wikipedia', 'wiki': None} ,
{'name': 'Banjul', 'key': 'Port of Banjul wikipedia', 'wiki': None} ,
{'name': 'Batumi', 'key': 'Port of Batumi wikipedia', 'wiki': None} ,
{'name': 'Poti', 'key': 'Port of Poti wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Poti_Sea_Port'} ,
{'name': 'Sukhumi', 'key': 'Port of Sukhumi wikipedia', 'wiki': None} ,
{'name': 'Brake', 'key': 'Port of Brake wikipedia', 'wiki': None} ,
{'name': 'Bremen', 'key': 'Port of Bremen wikipedia', 'wiki': None} ,
{'name': 'Bremerhaven', 'key': 'Port of Bremerhaven wikipedia', 'wiki': None} ,
{'name': 'Duisburg', 'key': 'Port of Duisburg wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Duisburg_Inner_Harbour'} ,
{'name': 'Dusseldorf', 'key': 'Port of Dusseldorf wikipedia', 'wiki': None} ,
{'name': 'Emden', 'key': 'Port of Emden wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Emden'} ,
{'name': 'Hamburg', 'key': 'Port of Hamburg wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hamburg'} ,
{'name': 'Karlsruhe', 'key': 'Port of Karlsruhe wikipedia', 'wiki': None} ,
{'name': 'Kiel', 'key': 'Port of Kiel wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Kiel'} ,
{'name': 'Lubeck', 'key': 'Port of Lubeck wikipedia', 'wiki': None} ,
{'name': 'Mannheim', 'key': 'Port of Mannheim wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Mannheim_Harbour'} ,
{'name': 'Rostock', 'key': 'Port of Rostock wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Rostock_Port'} ,
{'name': 'Wilhelmshavn', 'key': 'Port of Wilhelmshavn wikipedia', 'wiki': None} ,
{'name': 'Takoradi', 'key': 'Port of Takoradi wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Takoradi_Harbour'} ,
{'name': 'Tema', 'key': 'Port of Tema wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Tema_Harbour'} ,
{'name': 'Gibraltar', 'key': 'Port of Gibraltar wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Gibraltar'} ,
{'name': 'Eleusis', 'key': 'Port of Eleusis wikipedia', 'wiki': None} ,
{'name': 'Iraklion (Heraklion)', 'key': 'Port of Iraklion (Heraklion) wikipedia', 'wiki': None} ,
{'name': 'Kavala', 'key': 'Port of Kavala wikipedia', 'wiki': None} ,
{'name': 'Patras', 'key': 'Port of Patras wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Piraeus'} ,
{'name': 'Piraeus', 'key': 'Port of Piraeus wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Piraeus'} ,
{'name': 'Thessaloniki', 'key': 'Port of Thessaloniki wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Thessaloniki'} ,
{'name': 'Volos', 'key': 'Port of Volos wikipedia', 'wiki': None} ,
{'name': 'Holsteinsborg (Sisimiut)', 'key': 'Port of Holsteinsborg (Sisimiut) wikipedia', 'wiki': None} ,
{'name': 'Nanortalik', 'key': 'Port of Nanortalik wikipedia', 'wiki': None} ,
{'name': 'Narsarsuaq', 'key': 'Port of Narsarsuaq wikipedia', 'wiki': None} ,
{'name': 'Nuuk (Godthaab)', 'key': 'Port of Nuuk (Godthaab) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Nuuk_Port_and_Harbour'} ,
{'name': 'Gustavia', 'key': 'Port of Gustavia wikipedia', 'wiki': None} ,
{'name': 'Pointe-a-Pitre', 'key': 'Port of Pointe-a-Pitre wikipedia', 'wiki': None} ,
{'name': 'Apra (Agana)', 'key': 'Port of Apra (Agana) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Apra_Harbor'} ,
{'name': 'Champerico', 'key': 'Port of Champerico wikipedia', 'wiki': None} ,
{'name': 'Puerto Barrios', 'key': 'Port of Puerto Barrios wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Barrios'} ,
{'name': 'Santo Tomas De Castilla', 'key': 'Port of Santo Tomas De Castilla wikipedia', 'wiki': None} ,
{'name': 'Conakry', 'key': 'Port of Conakry wikipedia', 'wiki': None} ,
{'name': 'Port Kamsar', 'key': 'Port of Port Kamsar wikipedia', 'wiki': None} ,
{'name': 'Bissau', 'key': 'Port of Bissau wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Bissau'} ,
{'name': 'Georgetown', 'key': 'Port of Georgetown wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Penang'} ,
{'name': 'New Amsterdam', 'key': 'Port of New Amsterdam wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Amsterdam'} ,
{'name': 'Port Au Prince', 'key': 'Port of Port Au Prince wikipedia', 'wiki': None} ,
{'name': 'La Ceiba', 'key': 'Port of La Ceiba wikipedia', 'wiki': None} ,
{'name': 'Puerto Castilla', 'key': 'Port of Puerto Castilla wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Castilla,_Honduras'} ,
{'name': 'Puerto Cortes', 'key': 'Port of Puerto Cortes wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Cort%C3%A9s'} ,
{'name': 'San Lorenzo', 'key': 'Port of San Lorenzo wikipedia', 'wiki': None} ,
{'name': 'Tela', 'key': 'Port of Tela wikipedia', 'wiki': None} ,
{'name': 'Hong Kong', 'key': 'Port of Hong Kong wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hong_Kong'} ,
{'name': 'Akureyri', 'key': 'Port of Akureyri wikipedia', 'wiki': None} ,
{'name': 'Hafnarfjordur (Straumsvik)', 'key': 'Port of Hafnarfjordur (Straumsvik) wikipedia', 'wiki': None} ,
{'name': 'Isafjordur', 'key': 'Port of Isafjordur wikipedia', 'wiki': None} ,
{'name': 'Keflavik', 'key': 'Port of Keflavik wikipedia', 'wiki': None} ,
{'name': 'Reykjavik', 'key': 'Port of Reykjavik wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Finnafjord_Port'} ,
{'name': 'Vestmannaeyjar', 'key': 'Port of Vestmannaeyjar wikipedia', 'wiki': None} ,
{'name': 'Bombay (Mumbai)', 'key': 'Port of Bombay (Mumbai) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Mumbai_Harbour'} ,
{'name': 'Calcutta (Kolkata)', 'key': 'Port of Calcutta (Kolkata) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Kolkata'} ,
{'name': 'Chennai (Madras)', 'key': 'Port of Chennai (Madras) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Chennai_Port'} ,
{'name': 'Cochin', 'key': 'Port of Cochin wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Cochin_Port'} ,
{'name': 'Kandla', 'key': 'Port of Kandla wikipedia', 'wiki': None} ,
{'name': 'Nhava Sheva (Jawaharlal Nehru)', 'key': 'Port of Nhava Sheva (Jawaharlal Nehru) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Jawaharlal_Nehru_Port'} ,
{'name': 'Tuticorin', 'key': 'Port of Tuticorin wikipedia', 'wiki': None} ,
{'name': 'Vishakhapatnam', 'key': 'Port of Vishakhapatnam wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Visakhapatnam_Port'} ,
{'name': 'Cilacap, Java (Tanjung Intan)', 'key': 'Port of Cilacap, Java (Tanjung Intan) wikipedia', 'wiki': None} ,
{'name': 'Cirebon, Java', 'key': 'Port of Cirebon, Java wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cirebon'} ,
{'name': 'Jakarta, Java  (Tanjung Priok)', 'key': 'Port of Jakarta, Java  (Tanjung Priok) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tanjung_Priok'} ,
{'name': 'Kupang, Timor', 'key': 'Port of Kupang, Timor wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Dili'} ,
{'name': 'Palembang, Sumatra', 'key': 'Port of Palembang, Sumatra wikipedia', 'wiki': None} ,
{'name': 'Semarang, Java (Tanjung Emas)', 'key': 'Port of Semarang, Java (Tanjung Emas) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tanjung_Emas'} ,
{'name': 'Surabaya, Java (Tanjung Perak)', 'key': 'Port of Surabaya, Java (Tanjung Perak) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tanjung_Perak'} ,
{'name': 'Ujung Pandang, Sulawesi (Makassar)', 'key': 'Port of Ujung Pandang, Sulawesi (Makassar) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Makassar'} ,
{'name': 'Abadan', 'key': 'Port of Abadan wikipedia', 'wiki': None} ,
{'name': 'Bandar Abbas', 'key': 'Port of Bandar Abbas wikipedia', 'wiki': None} ,
{'name': 'Bandar Anzali', 'key': 'Port of Bandar Anzali wikipedia', 'wiki': None} ,
{'name': 'Bandar Mahshahr', 'key': 'Port of Bandar Mahshahr wikipedia', 'wiki': None} ,
{'name': 'Bushehr', 'key': 'Port of Bushehr wikipedia', 'wiki': None} ,
{'name': 'Imam Khomeini', 'key': 'Port of Imam Khomeini wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Amirabad_Port'} ,
{'name': 'Khorramshahr', 'key': 'Port of Khorramshahr wikipedia', 'wiki': None} ,
{'name': 'Lavan', 'key': 'Port of Lavan wikipedia', 'wiki': None} ,
{'name': 'Sirri Island', 'key': 'Port of Sirri Island wikipedia', 'wiki': None} ,
{'name': 'Basra', 'key': 'Port of Basra wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Basra'} ,
{'name': 'Khor al Zubair', 'key': 'Port of Khor al Zubair wikipedia', 'wiki': None} ,
{'name': 'Umm Qasr', 'key': 'Port of Umm Qasr wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Umm_Qasr_Port'} ,
{'name': 'Arklow', 'key': 'Port of Arklow wikipedia', 'wiki': None} ,
{'name': 'Cork', 'key': 'Port of Cork wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cork'} ,
{'name': 'Drogheda', 'key': 'Port of Drogheda wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Bremore_Port'} ,
{'name': 'Dublin', 'key': 'Port of Dublin wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Dublin_Port'} ,
{'name': 'Foynes (Shannon Foynes)', 'key': 'Port of Foynes (Shannon Foynes) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Shannon_Foynes_Port'} ,
{'name': 'Galway', 'key': 'Port of Galway wikipedia', 'wiki': None} ,
{'name': 'New Ross', 'key': 'Port of New Ross wikipedia', 'wiki': None} ,
{'name': 'Waterford', 'key': 'Port of Waterford wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Waterford_Harbour'} ,
{'name': 'Ashdod', 'key': 'Port of Ashdod wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ashdod'} ,
{'name': 'Ashkelon', 'key': 'Port of Ashkelon wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ashdod'} ,
{'name': 'Eilat', 'key': 'Port of Eilat wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Eilat'} ,
{'name': 'Hadera', 'key': 'Port of Hadera wikipedia', 'wiki': None} ,
{'name': 'Haifa', 'key': 'Port of Haifa wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Haifa'} ,
{'name': 'Augusta', 'key': 'Port of Augusta wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Augusta'} ,
{'name': 'Bagnoli', 'key': 'Port of Bagnoli wikipedia', 'wiki': None} ,
{'name': 'Bari', 'key': 'Port of Bari wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Bari'} ,
{'name': 'Brindisi', 'key': 'Port of Brindisi wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Brindisi'} ,
{'name': 'Gela', 'key': 'Port of Gela wikipedia', 'wiki': None} ,
{'name': 'Genoa', 'key': 'Port of Genoa wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Genoa'} ,
{'name': 'La Spezia', 'key': 'Port of La Spezia wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_La_Spezia'} ,
{'name': 'Livorno', 'key': 'Port of Livorno wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Livorno'} ,
{'name': 'Messina', 'key': 'Port of Messina wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Messina'} ,
{'name': 'Milazzo', 'key': 'Port of Milazzo wikipedia', 'wiki': None} ,
{'name': 'Napoli (Naples)', 'key': 'Port of Napoli (Naples) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Naples'} ,
{'name': 'Palermo', 'key': 'Port of Palermo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Palermo'} ,
{'name': 'Porto Torres', 'key': 'Port of Porto Torres wikipedia', 'wiki': None} ,
{'name': 'Ravenna', 'key': 'Port of Ravenna wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ravenna'} ,
{'name': 'Sarroch (Porto Foxi)', 'key': 'Port of Sarroch (Porto Foxi) wikipedia', 'wiki': None} ,
{'name': 'Savona-Vado', 'key': 'Port of Savona-Vado wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Savona'} ,
{'name': 'Taranto', 'key': 'Port of Taranto wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Taranto'} ,
{'name': 'Trieste', 'key': 'Port of Trieste wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Trieste'} ,
{'name': 'Venice', 'key': 'Port of Venice wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Venice'} ,
{'name': 'Kingston', 'key': 'Port of Kingston wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Kingston_Harbour'} ,
{'name': 'Montego Bay', 'key': 'Port of Montego Bay wikipedia', 'wiki': None} ,
{'name': 'Ocho Rios', 'key': 'Port of Ocho Rios wikipedia', 'wiki': None} ,
{'name': 'Port Antonio', 'key': 'Port of Port Antonio wikipedia', 'wiki': None} ,
{'name': 'Port Esquivel', 'key': 'Port of Port Esquivel wikipedia', 'wiki': None} ,
{'name': 'Rocky Point', 'key': 'Port of Rocky Point wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Pe%C3%B1asco'} ,
{'name': 'Akita', 'key': 'Port of Akita wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Akita'} ,
{'name': 'Amagasaki', 'key': 'Port of Amagasaki wikipedia', 'wiki': None} ,
{'name': 'Chiba', 'key': 'Port of Chiba wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Chiba'} ,
{'name': 'Hachinohe', 'key': 'Port of Hachinohe wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hachinohe'} ,
{'name': 'Hakodate, Hokkaido', 'key': 'Port of Hakodate, Hokkaido wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hakodate'} ,
{'name': 'Higashiharima', 'key': 'Port of Higashiharima wikipedia', 'wiki': None} ,
{'name': 'Himeji', 'key': 'Port of Himeji wikipedia', 'wiki': None} ,
{'name': 'Hiroshima', 'key': 'Port of Hiroshima wikipedia', 'wiki': None} ,
{'name': 'Kawasaki', 'key': 'Port of Kawasaki wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Yokohama'} ,
{'name': 'Kinuura', 'key': 'Port of Kinuura wikipedia', 'wiki': None} ,
{'name': 'Kobe', 'key': 'Port of Kobe wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Kobe'} ,
{'name': 'Kushiro, Hokkaido', 'key': 'Port of Kushiro, Hokkaido wikipedia', 'wiki': None} ,
{'name': 'Mizushima', 'key': 'Port of Mizushima wikipedia', 'wiki': None} ,
{'name': 'Moji', 'key': 'Port of Moji wikipedia', 'wiki': None} ,
{'name': 'Nagoya', 'key': 'Port of Nagoya wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Nagoya'} ,
{'name': 'Osaka', 'key': 'Port of Osaka wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Osaka'} ,
{'name': 'Sakai', 'key': 'Port of Sakai wikipedia', 'wiki': None} ,
{'name': 'Sakata', 'key': 'Port of Sakata wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Sakata'} ,
{'name': 'Shimizu', 'key': 'Port of Shimizu wikipedia', 'wiki': None} ,
{'name': 'Tokyo', 'key': 'Port of Tokyo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tokyo'} ,
{'name': 'Tomakomai, Hokkaido', 'key': 'Port of Tomakomai, Hokkaido wikipedia', 'wiki': None} ,
{'name': 'Yokohama', 'key': 'Port of Yokohama wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Yokohama'} ,
{'name': 'Aqaba (El Akaba)', 'key': 'Port of Aqaba (El Akaba) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Aqaba'} ,
{'name': 'Lamu', 'key': 'Port of Lamu wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Kilindini_Harbour'} ,
{'name': 'Mombasa', 'key': 'Port of Mombasa wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Kilindini_Harbour'} ,
{'name': 'Betio (Tarawa)', 'key': 'Port of Betio (Tarawa) wikipedia', 'wiki': None} ,
{'name': 'Chongjin', 'key': 'Port of Chongjin wikipedia', 'wiki': None} ,
{'name': 'Haeju', 'key': 'Port of Haeju wikipedia', 'wiki': None} ,
{'name': 'Nampo', 'key': 'Port of Nampo wikipedia', 'wiki': None} ,
{'name': 'Wonsan', 'key': 'Port of Wonsan wikipedia', 'wiki': None} ,
{'name': 'Busan (Pusan)', 'key': 'Port of Busan (Pusan) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Busan'} ,
{'name': 'Chinhae', 'key': 'Port of Chinhae wikipedia', 'wiki': None} ,
{'name': 'Inchon', 'key': 'Port of Inchon wikipedia', 'wiki': None} ,
{'name': 'Masan', 'key': 'Port of Masan wikipedia', 'wiki': None} ,
{'name': 'Mokpo', 'key': 'Port of Mokpo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Mokpo'} ,
{'name': 'Pohang', 'key': 'Port of Pohang wikipedia', 'wiki': None} ,
{'name': 'Tonghae', 'key': 'Port of Tonghae wikipedia', 'wiki': None} ,
{'name': 'Ulsan', 'key': 'Port of Ulsan wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ulsan'} ,
{'name': 'Yosu (Yeosu)', 'key': 'Port of Yosu (Yeosu) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Yeosu'} ,
{'name': 'Mina al Ahmadi', 'key': 'Port of Mina al Ahmadi wikipedia', 'wiki': None} ,
{'name': 'Mina Saud', 'key': 'Port of Mina Saud wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/King_Abdul_Aziz_Port'} ,
{'name': 'Shuwaikh', 'key': 'Port of Shuwaikh wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Shuwaikh_Port'} ,
{'name': 'Liepaja', 'key': 'Port of Liepaja wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Liep%C4%81ja'} ,
{'name': 'Riga', 'key': 'Port of Riga wikipedia', 'wiki': None} ,
{'name': 'Ventspils', 'key': 'Port of Ventspils wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ventspils'} ,
{'name': 'Beirut', 'key': 'Port of Beirut wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Beirut'} ,
{'name': 'Chekka', 'key': 'Port of Chekka wikipedia', 'wiki': None} ,
{'name': 'Selaata', 'key': 'Port of Selaata wikipedia', 'wiki': None} ,
{'name': 'Sidon', 'key': 'Port of Sidon wikipedia', 'wiki': None} ,
{'name': 'Tripoli', 'key': 'Port of Tripoli wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tripoli'} ,
{'name': 'Buchanan', 'key': 'Port of Buchanan wikipedia', 'wiki': None} ,
{'name': 'Greenville', 'key': 'Port of Greenville wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Inland_port'} ,
{'name': 'Monrovia', 'key': 'Port of Monrovia wikipedia', 'wiki': None} ,
{'name': 'Bingazi (Benghazi)', 'key': 'Port of Bingazi (Benghazi) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Benghazi'} ,
{'name': 'Derna', 'key': 'Port of Derna wikipedia', 'wiki': None} ,
{'name': 'Marsa El Brega', 'key': 'Port of Marsa El Brega wikipedia', 'wiki': None} ,
{'name': 'Misurata (Qasr Ahmed)', 'key': 'Port of Misurata (Qasr Ahmed) wikipedia', 'wiki': None} ,
{'name': 'Ras Lanuf', 'key': 'Port of Ras Lanuf wikipedia', 'wiki': None} ,
{'name': 'Tobruk', 'key': 'Port of Tobruk wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tobruk'} ,
{'name': 'Tripoli', 'key': 'Port of Tripoli wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tripoli'} ,
{'name': 'Zuara', 'key': 'Port of Zuara wikipedia', 'wiki': None} ,
{'name': 'Klaipeda', 'key': 'Port of Klaipeda wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Klaip%C4%97da'} ,
{'name': 'Macau', 'key': 'Port of Macau wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Macau'} ,
{'name': 'Antsiranana (Diego Suarez)', 'key': 'Port of Antsiranana (Diego Suarez) wikipedia', 'wiki': None} ,
{'name': 'Majunga (Mahajanga)', 'key': 'Port of Majunga (Mahajanga) wikipedia', 'wiki': None} ,
{'name': 'Toamasina (Tamatave)', 'key': 'Port of Toamasina (Tamatave) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Toamasina_Autonomous_Port'} ,
{'name': 'Tulear (Toliara)', 'key': 'Port of Tulear (Toliara) wikipedia', 'wiki': None} ,
{'name': 'Bintulu, Sarawak', 'key': 'Port of Bintulu, Sarawak wikipedia', 'wiki': None} ,
{'name': 'Kota Kinabalu, Sabah', 'key': 'Port of Kota Kinabalu, Sabah wikipedia', 'wiki': None} ,
{'name': 'Kuantan (Tanjong Gelang)', 'key': 'Port of Kuantan (Tanjong Gelang) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Kuantan_Port'} ,
{'name': 'Kuching, Sarawak', 'key': 'Port of Kuching, Sarawak wikipedia', 'wiki': None} ,
{'name': 'Kudat, Sabah', 'key': 'Port of Kudat, Sabah wikipedia', 'wiki': None} ,
{'name': 'Labuan, Sabah', 'key': 'Port of Labuan, Sabah wikipedia', 'wiki': None} ,
{'name': 'Lahad Datu, Sabah', 'key': 'Port of Lahad Datu, Sabah wikipedia', 'wiki': None} ,
{'name': 'Lumut', 'key': 'Port of Lumut wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Lumut_Port'} ,
{'name': 'Miri, Sarawak', 'key': 'Port of Miri, Sarawak wikipedia', 'wiki': None} ,
{'name': 'Pasir Gudang, Johor', 'key': 'Port of Pasir Gudang, Johor wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Johor_Port'} ,
{'name': 'Penang (Georgetown)', 'key': 'Port of Penang (Georgetown) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Penang'} ,
{'name': 'Port Dickson', 'key': 'Port of Port Dickson wikipedia', 'wiki': None} ,
{'name': 'Port Klang (Kelang)', 'key': 'Port of Port Klang (Kelang) wikipedia', 'wiki': None} ,
{'name': 'Sandakan, Sabah', 'key': 'Port of Sandakan, Sabah wikipedia', 'wiki': None} ,
{'name': 'Sibu, Sarawak', 'key': 'Port of Sibu, Sarawak wikipedia', 'wiki': None} ,
{'name': 'Tanjung Pelepas, Johor', 'key': 'Port of Tanjung Pelepas, Johor wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tanjung_Pelepas'} ,
{'name': 'Tawau, Sabah', 'key': 'Port of Tawau, Sabah wikipedia', 'wiki': None} ,
{'name': 'Valletta', 'key': 'Port of Valletta wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Grand_Harbour'} ,
{'name': 'Fort de France', 'key': 'Port of Fort de France wikipedia', 'wiki': None} ,
{'name': 'Nouadhibou', 'key': 'Port of Nouadhibou wikipedia', 'wiki': None} ,
{'name': 'Nouakchott', 'key': 'Port of Nouakchott wikipedia', 'wiki': None} ,
{'name': 'Port Louis', 'key': 'Port of Port Louis wikipedia', 'wiki': None} ,
{'name': 'Acapulco', 'key': 'Port of Acapulco wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Marqu%C3%A9s'} ,
{'name': 'Coatzacoalcos', 'key': 'Port of Coatzacoalcos wikipedia', 'wiki': None} ,
{'name': 'Guaymas', 'key': 'Port of Guaymas wikipedia', 'wiki': None} ,
{'name': 'La Paz', 'key': 'Port of La Paz wikipedia', 'wiki': None} ,
{'name': 'Lazaro Cardenas', 'key': 'Port of Lazaro Cardenas wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_L%C3%A1zaro_C%C3%A1rdenas'} ,
{'name': 'Manzanillo', 'key': 'Port of Manzanillo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Manzanillo'} ,
{'name': 'Mazatlan', 'key': 'Port of Mazatlan wikipedia', 'wiki': None} ,
{'name': 'Progreso', 'key': 'Port of Progreso wikipedia', 'wiki': None} ,
{'name': 'Salina Cruz', 'key': 'Port of Salina Cruz wikipedia', 'wiki': None} ,
{'name': 'Tampico', 'key': 'Port of Tampico wikipedia', 'wiki': None} ,
{'name': 'Topolobampo', 'key': 'Port of Topolobampo wikipedia', 'wiki': None} ,
{'name': 'Tuxpan', 'key': 'Port of Tuxpan wikipedia', 'wiki': None} ,
{'name': 'Veracruz', 'key': 'Port of Veracruz wikipedia', 'wiki': None} ,
{'name': 'Pohnpei (Ex Ponape)', 'key': 'Port of Pohnpei (Ex Ponape) wikipedia', 'wiki': None} ,
{'name': 'Monaco', 'key': 'Port of Monaco wikipedia', 'wiki': None} ,
{'name': 'Bar', 'key': 'Port of Bar wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Bar'} ,
{'name': 'Kotor', 'key': 'Port of Kotor wikipedia', 'wiki': None} ,
{'name': 'Plymouth', 'key': 'Port of Plymouth wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Plymouth_Harbor'} ,
{'name': 'Agadir', 'key': 'Port of Agadir wikipedia', 'wiki': None} ,
{'name': 'Casablanca', 'key': 'Port of Casablanca wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Casablanca'} ,
{'name': 'El Jadida', 'key': 'Port of El Jadida wikipedia', 'wiki': None} ,
{'name': 'Kenitra', 'key': 'Port of Kenitra wikipedia', 'wiki': None} ,
{'name': 'Mohammedia', 'key': 'Port of Mohammedia wikipedia', 'wiki': None} ,
{'name': 'Safi', 'key': 'Port of Safi wikipedia', 'wiki': None} ,
{'name': 'Tangier', 'key': 'Port of Tangier wikipedia', 'wiki': None} ,
{'name': 'Beira', 'key': 'Port of Beira wikipedia', 'wiki': None} ,
{'name': 'Inhambane', 'key': 'Port of Inhambane wikipedia', 'wiki': None} ,
{'name': 'Maputo', 'key': 'Port of Maputo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Maputo'} ,
{'name': 'Nacala', 'key': 'Port of Nacala wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Nacala'} ,
{'name': 'Pemba', 'key': 'Port of Pemba wikipedia', 'wiki': None} ,
{'name': 'Quelimane', 'key': 'Port of Quelimane wikipedia', 'wiki': None} ,
{'name': 'Bassein', 'key': 'Port of Bassein wikipedia', 'wiki': None} ,
{'name': 'Moulmein', 'key': 'Port of Moulmein wikipedia', 'wiki': None} ,
{'name': 'Yangon', 'key': 'Port of Yangon wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Thilawa_Port'} ,
{'name': 'Luderitz', 'key': 'Port of Luderitz wikipedia', 'wiki': None} ,
{'name': 'Walvis Bay', 'key': 'Port of Walvis Bay wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Sandwich_Harbour'} ,
{'name': 'Nauru Island', 'key': 'Port of Nauru Island wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Nauru_International_Port'} ,
{'name': 'Amsterdam', 'key': 'Port of Amsterdam wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Amsterdam'} ,
{'name': 'Delfzijl', 'key': 'Port of Delfzijl wikipedia', 'wiki': None} ,
{'name': 'Dordrecht', 'key': 'Port of Dordrecht wikipedia', 'wiki': None} ,
{'name': 'Eemshaven', 'key': 'Port of Eemshaven wikipedia', 'wiki': None} ,
{'name': 'Groningen', 'key': 'Port of Groningen wikipedia', 'wiki': None} ,
{'name': 'IJmuiden', 'key': 'Port of IJmuiden wikipedia', 'wiki': None} ,
{'name': 'Rotterdam', 'key': 'Port of Rotterdam wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rotterdam'} ,
{'name': 'Terneuzen', 'key': 'Port of Terneuzen wikipedia', 'wiki': None} ,
{'name': 'Kralendijk, Bonaire', 'key': 'Port of Kralendijk, Bonaire wikipedia', 'wiki': None} ,
{'name': 'Philipsburg', 'key': 'Port of Philipsburg wikipedia', 'wiki': None} ,
{'name': 'Willemstad', 'key': 'Port of Willemstad wikipedia', 'wiki': None} ,
{'name': 'Noumea', 'key': 'Port of Noumea wikipedia', 'wiki': None} ,
{'name': 'Thio', 'key': 'Port of Thio wikipedia', 'wiki': None} ,
{'name': 'Auckland', 'key': 'Port of Auckland wikipedia', 'wiki': None} ,
{'name': 'Otago Harbour', 'key': 'Port of Otago Harbour wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Otago_Harbour'} ,
{'name': '(Dunedin, Port Chalmers, Ravensbourne)', 'key': 'Port of (Dunedin, Port Chalmers, Ravensbourne) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Otago_Harbour'} ,
{'name': 'Tauranga', 'key': 'Port of Tauranga wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tauranga'} ,
{'name': 'Wellington', 'key': 'Port of Wellington wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Wellington_Harbour'} ,
{'name': 'Bluefields', 'key': 'Port of Bluefields wikipedia', 'wiki': None} ,
{'name': 'Corinto', 'key': 'Port of Corinto wikipedia', 'wiki': None} ,
{'name': 'El Bluff', 'key': 'Port of El Bluff wikipedia', 'wiki': None} ,
{'name': 'Puerto Cabezas', 'key': 'Port of Puerto Cabezas wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Cabezas'} ,
{'name': 'Puerto Sandino', 'key': 'Port of Puerto Sandino wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Sandino'} ,
{'name': 'San Juan Del Sur', 'key': 'Port of San Juan Del Sur wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_San_Juan'} ,
{'name': 'Calabar', 'key': 'Port of Calabar wikipedia', 'wiki': None} ,
{'name': 'Lagos', 'key': 'Port of Lagos wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Tin_Can_Island_Port'} ,
{'name': 'Onne', 'key': 'Port of Onne wikipedia', 'wiki': None} ,
{'name': 'Port Harcourt', 'key': 'Port of Port Harcourt wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Port_Harcourt'} ,
{'name': 'Sapele', 'key': 'Port of Sapele wikipedia', 'wiki': None} ,
{'name': 'Tin Can Island', 'key': 'Port of Tin Can Island wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Tin_Can_Island_Port'} ,
{'name': 'Warri', 'key': 'Port of Warri wikipedia', 'wiki': None} ,
{'name': 'Saipan', 'key': 'Port of Saipan wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Tanapag_Harbor'} ,
{'name': 'Bergen', 'key': 'Port of Bergen wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Bergen_Port'} ,
{'name': 'Drammen', 'key': 'Port of Drammen wikipedia', 'wiki': None} ,
{'name': 'Grenland Harbour', 'key': 'Port of Grenland Harbour wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Grenland_Harbour'} ,
{'name': 'Hammerfest', 'key': 'Port of Hammerfest wikipedia', 'wiki': None} ,
{'name': 'Harstad', 'key': 'Port of Harstad wikipedia', 'wiki': None} ,
{'name': 'Haugesund', 'key': 'Port of Haugesund wikipedia', 'wiki': None} ,
{'name': 'Kristiansand', 'key': 'Port of Kristiansand wikipedia', 'wiki': None} ,
{'name': 'Larvik', 'key': 'Port of Larvik wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Larvik_Harbour'} ,
{'name': 'Oslo', 'key': 'Port of Oslo wikipedia', 'wiki': None} ,
{'name': 'Stavanger', 'key': 'Port of Stavanger wikipedia', 'wiki': None} ,
{'name': 'Trondheim', 'key': 'Port of Trondheim wikipedia', 'wiki': None} ,
{'name': 'Karachi', 'key': 'Port of Karachi wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Karachi'} ,
{'name': 'Muhammad Bin Qasim', 'key': 'Port of Muhammad Bin Qasim wikipedia', 'wiki': None} ,
{'name': 'Colon', 'key': 'Port of Colon wikipedia', 'wiki': None} ,
{'name': 'Cristobal', 'key': 'Port of Cristobal wikipedia', 'wiki': None} ,
{'name': 'Vacamonte', 'key': 'Port of Vacamonte wikipedia', 'wiki': None} ,
{'name': 'Kieta', 'key': 'Port of Kieta wikipedia', 'wiki': None} ,
{'name': 'Lae', 'key': 'Port of Lae wikipedia', 'wiki': None} ,
{'name': 'Madang', 'key': 'Port of Madang wikipedia', 'wiki': None} ,
{'name': 'Port Moresby', 'key': 'Port of Port Moresby wikipedia', 'wiki': None} ,
{'name': 'Rabaul', 'key': 'Port of Rabaul wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Simpson_Harbour'} ,
{'name': 'Callao', 'key': 'Port of Callao wikipedia', 'wiki': None} ,
{'name': 'Chimbote', 'key': 'Port of Chimbote wikipedia', 'wiki': None} ,
{'name': 'Ilo', 'key': 'Port of Ilo wikipedia', 'wiki': None} ,
{'name': 'Matarani', 'key': 'Port of Matarani wikipedia', 'wiki': None} ,
{'name': 'Paita', 'key': 'Port of Paita wikipedia', 'wiki': None} ,
{'name': 'Salaverry', 'key': 'Port of Salaverry wikipedia', 'wiki': None} ,
{'name': 'Talara', 'key': 'Port of Talara wikipedia', 'wiki': None} ,
{'name': 'Batangas', 'key': 'Port of Batangas wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Batangas_International_Port'} ,
{'name': 'Cagayan de Oro,Mindanao', 'key': 'Port of Cagayan de Oro,Mindanao wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cagayan_de_Oro'} ,
{'name': 'Cebu', 'key': 'Port of Cebu wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cebu'} ,
{'name': 'Davao, Mindanao', 'key': 'Port of Davao, Mindanao wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Davao'} ,
{'name': 'Iligan, Mindanao', 'key': 'Port of Iligan, Mindanao wikipedia', 'wiki': None} ,
{'name': 'Iloilo', 'key': 'Port of Iloilo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Iloilo'} ,
{'name': 'Jolo', 'key': 'Port of Jolo wikipedia', 'wiki': None} ,
{'name': 'Legaspi, Davao', 'key': 'Port of Legaspi, Davao wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Davao'} ,
{'name': 'Manila', 'key': 'Port of Manila wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Manila'} ,
{'name': 'Puerto Princesa, Palawan', 'key': 'Port of Puerto Princesa, Palawan wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Puerto_Princesa'} ,
{'name': 'San Fernando, Luzon', 'key': 'Port of San Fernando, Luzon wikipedia', 'wiki': None} ,
{'name': 'Subic Bay', 'key': 'Port of Subic Bay wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Subic_Bay'} ,
{'name': 'Zamboanga, Mindanao', 'key': 'Port of Zamboanga, Mindanao wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Zamboanga'} ,
{'name': 'Gdansk', 'key': 'Port of Gdansk wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Gda%C5%84sk'} ,
{'name': 'Gdynia', 'key': 'Port of Gdynia wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Gdynia'} ,
{'name': 'Kolobrzeg', 'key': 'Port of Kolobrzeg wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ko%C5%82obrzeg'} ,
{'name': 'Swinoujscie', 'key': 'Port of Swinoujscie wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_%C5%9Awinouj%C5%9Bcie'} ,
{'name': 'Szczecin', 'key': 'Port of Szczecin wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Szczecin'} ,
{'name': 'Ustka', 'key': 'Port of Ustka wikipedia', 'wiki': None} ,
{'name': 'Aveiro', 'key': 'Port of Aveiro wikipedia', 'wiki': None} ,
{'name': 'Leixoes', 'key': 'Port of Leixoes wikipedia', 'wiki': None} ,
{'name': 'Lisbon', 'key': 'Port of Lisbon wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Lisbon'} ,
{'name': 'Portimao', 'key': 'Port of Portimao wikipedia', 'wiki': None} ,
{'name': 'Setubal', 'key': 'Port of Setubal wikipedia', 'wiki': None} ,
{'name': 'Viana Do Castelo', 'key': 'Port of Viana Do Castelo wikipedia', 'wiki': None} ,
{'name': 'Guanica Harbour', 'key': 'Port of Guanica Harbour wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Rico_campaign'} ,
{'name': 'Guayanilla', 'key': 'Port of Guayanilla wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Rico_Ports_Authority'} ,
{'name': 'Las Mareas', 'key': 'Port of Las Mareas wikipedia', 'wiki': None} ,
{'name': 'Ponce', 'key': 'Port of Ponce wikipedia', 'wiki': None} ,
{'name': 'San Juan', 'key': 'Port of San Juan wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_San_Juan'} ,
{'name': 'Doha', 'key': 'Port of Doha wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Doha_Port'} ,
{'name': 'Halul Island', 'key': 'Port of Halul Island wikipedia', 'wiki': None} ,
{'name': 'Ras Laffan', 'key': 'Port of Ras Laffan wikipedia', 'wiki': None} ,
{'name': 'Umm Said (Mesaieed)', 'key': 'Port of Umm Said (Mesaieed) wikipedia', 'wiki': None} ,
{'name': 'Port Reunion (Pointe des Galets)', 'key': 'Port of Port Reunion (Pointe des Galets) wikipedia', 'wiki': None} ,
{'name': 'Braila', 'key': 'Port of Braila wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Br%C4%83ila'} ,
{'name': 'Constantza', 'key': 'Port of Constantza wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Constan%C8%9Ba'} ,
{'name': 'Mangalia', 'key': 'Port of Mangalia wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Mangalia'} ,
{'name': 'Sulina', 'key': 'Port of Sulina wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Sulina'} ,
{'name': 'Kaliningrad', 'key': 'Port of Kaliningrad wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Primorsk'} ,
{'name': 'Kholmsk', 'key': 'Port of Kholmsk wikipedia', 'wiki': None} ,
{'name': 'Murmansk', 'key': 'Port of Murmansk wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Murmansk'} ,
{'name': 'Nakhodka', 'key': 'Port of Nakhodka wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Vostochny_Port'} ,
{'name': 'Novorossiysk', 'key': 'Port of Novorossiysk wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Novorossiysk'} ,
{'name': 'St Petersburg', 'key': 'Port of St Petersburg wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_St._Petersburg'} ,
{'name': 'Tuapse', 'key': 'Port of Tuapse wikipedia', 'wiki': None} ,
{'name': 'Vladivostok', 'key': 'Port of Vladivostok wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Vostochny_Port'} ,
{'name': 'Vyborg', 'key': 'Port of Vyborg wikipedia', 'wiki': None} ,
{'name': 'Basseterre', 'key': 'Port of Basseterre wikipedia', 'wiki': None} ,
{'name': 'Castries (St Lucia)', 'key': 'Port of Castries (St Lucia) wikipedia', 'wiki': None} ,
{'name': 'Vieux Fort', 'key': 'Port of Vieux Fort wikipedia', 'wiki': None} ,
{'name': 'Kingstown', 'key': 'Port of Kingstown wikipedia', 'wiki': None} ,
{'name': 'Apia', 'key': 'Port of Apia wikipedia', 'wiki': None} ,
{'name': 'Santo Antonio', 'key': 'Port of Santo Antonio wikipedia', 'wiki': None} ,
{'name': 'Sao Tome', 'key': 'Port of Sao Tome wikipedia', 'wiki': None} ,
{'name': 'Dammam', 'key': 'Port of Dammam wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/King_Abdul_Aziz_Port'} ,
{'name': 'Dhuba', 'key': 'Port of Dhuba wikipedia', 'wiki': None} ,
{'name': 'Gizan', 'key': 'Port of Gizan wikipedia', 'wiki': None} ,
{'name': 'Jeddah', 'key': 'Port of Jeddah wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Jeddah_Islamic_Port'} ,
{'name': 'Jubail', 'key': 'Port of Jubail wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/King_Abdul_Aziz_Port'} ,
{'name': 'Rabigh', 'key': 'Port of Rabigh wikipedia', 'wiki': None} ,
{'name': 'Ras al Mishab', 'key': 'Port of Ras al Mishab wikipedia', 'wiki': None} ,
{'name': 'Ras Tanura', 'key': 'Port of Ras Tanura wikipedia', 'wiki': None} ,
{'name': 'Yanbu', 'key': 'Port of Yanbu wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Yanbu_Commercial_Port'} ,
{'name': 'Dakar', 'key': 'Port of Dakar wikipedia', 'wiki': None} ,
{'name': 'Port Victoria', 'key': 'Port of Port Victoria wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Victoria'} ,
{'name': 'Freetown', 'key': 'Port of Freetown wikipedia', 'wiki': None} ,
{'name': 'Pepel', 'key': 'Port of Pepel wikipedia', 'wiki': None} ,
{'name': 'Singapore', 'key': 'Port of Singapore wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Singapore'} ,
{'name': 'Izola', 'key': 'Port of Izola wikipedia', 'wiki': None} ,
{'name': 'Koper', 'key': 'Port of Koper wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Koper'} ,
{'name': 'Piran', 'key': 'Port of Piran wikipedia', 'wiki': None} ,
{'name': 'Honiara', 'key': 'Port of Honiara wikipedia', 'wiki': None} ,
{'name': 'Noro, New Georgia', 'key': 'Port of Noro, New Georgia wikipedia', 'wiki': None} ,
{'name': 'Viru Harbour', 'key': 'Port of Viru Harbour wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Battle_of_Viru_Harbor'} ,
{'name': 'Yandina, Pavuvu Island', 'key': 'Port of Yandina, Pavuvu Island wikipedia', 'wiki': None} ,
{'name': 'Berbera', 'key': 'Port of Berbera wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Berbera'} ,
{'name': 'Kismayu', 'key': 'Port of Kismayu wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Kismayo'} ,
{'name': 'Merca', 'key': 'Port of Merca wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Merca'} ,
{'name': 'Mogadishu', 'key': 'Port of Mogadishu wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Mogadishu'} ,
{'name': 'Cape Town', 'key': 'Port of Cape Town wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cape_Town'} ,
{'name': 'Durban', 'key': 'Port of Durban wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Durban'} ,
{'name': 'Mossel Bay', 'key': 'Port of Mossel Bay wikipedia', 'wiki': None} ,
{'name': 'Port Elizabeth', 'key': 'Port of Port Elizabeth wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Port_Elizabeth'} ,
{'name': 'Richards Bay', 'key': 'Port of Richards Bay wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Richards_Bay'} ,
{'name': 'Saldanha Bay', 'key': 'Port of Saldanha Bay wikipedia', 'wiki': None} ,
{'name': 'Aviles', 'key': 'Port of Aviles wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Avil%C3%A9s'} ,
{'name': 'Barcelona', 'key': 'Port of Barcelona wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Barcelona'} ,
{'name': 'Bilbao', 'key': 'Port of Bilbao wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Bilbao'} ,
{'name': 'Cadiz', 'key': 'Port of Cadiz wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cadiz_Bay'} ,
{'name': 'Cartagena', 'key': 'Port of Cartagena wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cartagena'} ,
{'name': 'Castellon', 'key': 'Port of Castellon wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Valencia'} ,
{'name': 'Ceuta', 'key': 'Port of Ceuta wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Ceuta'} ,
{'name': 'Huelva', 'key': 'Port of Huelva wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Huelva'} ,
{'name': 'Malaga', 'key': 'Port of Malaga wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_M%C3%A1laga'} ,
{'name': 'Pasajes', 'key': 'Port of Pasajes wikipedia', 'wiki': None} ,
{'name': 'Santander', 'key': 'Port of Santander wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Santander,_Amazonas'} ,
{'name': 'Tarragona', 'key': 'Port of Tarragona wikipedia', 'wiki': None} ,
{'name': 'Valencia', 'key': 'Port of Valencia wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Valencia'} ,
{'name': 'Vigo', 'key': 'Port of Vigo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Vigo'} ,
{'name': 'Colombo', 'key': 'Port of Colombo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Colombo'} ,
{'name': 'Jaffna', 'key': 'Port of Jaffna wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Jambukola'} ,
{'name': 'Trincomalee', 'key': 'Port of Trincomalee wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Trincomalee_Harbour'} ,
{'name': 'Jamestown', 'key': 'Port of Jamestown wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Jamestown_Harbour'} ,
{'name': 'St Pierre', 'key': 'Port of St Pierre wikipedia', 'wiki': None} ,
{'name': 'Port Sudan', 'key': 'Port of Port Sudan wikipedia', 'wiki': None} ,
{'name': 'Moengo', 'key': 'Port of Moengo wikipedia', 'wiki': None} ,
{'name': 'Nieuw Nickerie', 'key': 'Port of Nieuw Nickerie wikipedia', 'wiki': None} ,
{'name': 'Paramaribo', 'key': 'Port of Paramaribo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Jules_Sedney_Harbour'} ,
{'name': 'Paranam', 'key': 'Port of Paranam wikipedia', 'wiki': None} ,
{'name': 'Wageningen', 'key': 'Port of Wageningen wikipedia', 'wiki': None} ,
{'name': 'Gavle', 'key': 'Port of Gavle wikipedia', 'wiki': None} ,
{'name': 'Gothenburg (Goteborg)', 'key': 'Port of Gothenburg (Goteborg) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Gothenburg'} ,
{'name': 'Halmstad', 'key': 'Port of Halmstad wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Norre_Port'} ,
{'name': 'Kalmar', 'key': 'Port of Kalmar wikipedia', 'wiki': None} ,
{'name': 'Karlshamn', 'key': 'Port of Karlshamn wikipedia', 'wiki': None} ,
{'name': 'Malmo', 'key': 'Port of Malmo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Copenhagen_Malm%C3%B6_Port'} ,
{'name': 'Solvesborg', 'key': 'Port of Solvesborg wikipedia', 'wiki': None} ,
{'name': 'Stockholm', 'key': 'Port of Stockholm wikipedia', 'wiki': None} ,
{'name': 'Sundsvall', 'key': 'Port of Sundsvall wikipedia', 'wiki': None} ,
{'name': 'Basel', 'key': 'Port of Basel wikipedia', 'wiki': None} ,
{'name': 'Baniyas', 'key': 'Port of Baniyas wikipedia', 'wiki': None} ,
{'name': 'Hualien', 'key': 'Port of Hualien wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hualien'} ,
{'name': 'Kaohsiung', 'key': 'Port of Kaohsiung wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Kaohsiung'} ,
{'name': 'Kaohsiung', 'key': 'Port of Kaohsiung wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Kaohsiung'} ,
{'name': 'Keelung (Chilung)', 'key': 'Port of Keelung (Chilung) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Keelung'} ,
{'name': 'Suao', 'key': 'Port of Suao wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Nanfang%27ao_Fishing_Port'} ,
{'name': 'Taichung', 'key': 'Port of Taichung wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Taichung'} ,
{'name': 'Dar Es Salaam', 'key': 'Port of Dar Es Salaam wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Dar_es_Salaam'} ,
{'name': 'Kilwa Masoko', 'key': 'Port of Kilwa Masoko wikipedia', 'wiki': None} ,
{'name': 'Lindi', 'key': 'Port of Lindi wikipedia', 'wiki': None} ,
{'name': 'Mtwara', 'key': 'Port of Mtwara wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Mtwara_Port'} ,
{'name': 'Pangani', 'key': 'Port of Pangani wikipedia', 'wiki': None} ,
{'name': 'Tanga', 'key': 'Port of Tanga wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tanga'} ,
{'name': 'Bangkok', 'key': 'Port of Bangkok wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Bangkok_Port'} ,
{'name': 'Laem Chabang', 'key': 'Port of Laem Chabang wikipedia', 'wiki': None} ,
{'name': 'Pattani', 'key': 'Port of Pattani wikipedia', 'wiki': None} ,
{'name': 'Phuket', 'key': 'Port of Phuket wikipedia', 'wiki': None} ,
{'name': 'Sattahip', 'key': 'Port of Sattahip wikipedia', 'wiki': None} ,
{'name': 'Songkhla', 'key': 'Port of Songkhla wikipedia', 'wiki': None} ,
{'name': 'Sriracha', 'key': 'Port of Sriracha wikipedia', 'wiki': None} ,
{'name': 'Kpeme', 'key': 'Port of Kpeme wikipedia', 'wiki': None} ,
{'name': 'Lome', 'key': 'Port of Lome wikipedia', 'wiki': None} ,
{'name': 'Neiafu', 'key': 'Port of Neiafu wikipedia', 'wiki': None} ,
{'name': 'Nukualofa', 'key': 'Port of Nukualofa wikipedia', 'wiki': None} ,
{'name': 'Pangai', 'key': 'Port of Pangai wikipedia', 'wiki': None} ,
{'name': 'Point Fortin', 'key': 'Port of Point Fortin wikipedia', 'wiki': None} ,
{'name': 'Point Lisas', 'key': 'Port of Point Lisas wikipedia', 'wiki': None} ,
{'name': 'Pointe a Pierre', 'key': 'Port of Pointe a Pierre wikipedia', 'wiki': None} ,
{'name': 'Scarborough', 'key': 'Port of Scarborough wikipedia', 'wiki': None} ,
{'name': 'Spain', 'key': 'Port of Spain wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Spain'} ,
{'name': 'Tembladora', 'key': 'Port of Tembladora wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Rotterdam'} ,
{'name': 'Bizerte', 'key': 'Port of Bizerte wikipedia', 'wiki': None} ,
{'name': 'Gabes', 'key': 'Port of Gabes wikipedia', 'wiki': None} ,
{'name': 'La Goulette', 'key': 'Port of La Goulette wikipedia', 'wiki': None} ,
{'name': 'Sfax', 'key': 'Port of Sfax wikipedia', 'wiki': None} ,
{'name': 'Sousse', 'key': 'Port of Sousse wikipedia', 'wiki': None} ,
{'name': 'Tunis', 'key': 'Port of Tunis wikipedia', 'wiki': None} ,
{'name': 'Derince', 'key': 'Port of Derince wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Haydarpa%C5%9Fa'} ,
{'name': 'Dikili', 'key': 'Port of Dikili wikipedia', 'wiki': None} ,
{'name': 'Gemlik', 'key': 'Port of Gemlik wikipedia', 'wiki': None} ,
{'name': 'Hopa, Artvin', 'key': 'Port of Hopa, Artvin wikipedia', 'wiki': None} ,
{'name': 'Iskenderun, Hatay', 'key': 'Port of Iskenderun, Hatay wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/%C4%B0skenderun_Harbor'} ,
{'name': 'Istanbul', 'key': 'Port of Istanbul wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Istanbul'} ,
{'name': 'Trabzon', 'key': 'Port of Trabzon wikipedia', 'wiki': None} ,
{'name': 'Grand Turk Island', 'key': 'Port of Grand Turk Island wikipedia', 'wiki': None} ,
{'name': 'Providenciales', 'key': 'Port of Providenciales wikipedia', 'wiki': None} ,
{'name': 'Funafuti', 'key': 'Port of Funafuti wikipedia', 'wiki': None} ,
{'name': 'Aberdeen', 'key': 'Port of Aberdeen wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Aberdeen_Harbour'} ,
{'name': 'Belfast', 'key': 'Port of Belfast wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Belfast_Harbour'} ,
{'name': 'Bristol', 'key': 'Port of Bristol wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Bristol'} ,
{'name': 'Dover', 'key': 'Port of Dover wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Dover'} ,
{'name': 'Falmouth', 'key': 'Port of Falmouth wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Falmouth_Harbour'} ,
{'name': 'Felixstowe', 'key': 'Port of Felixstowe wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Felixstowe'} ,
{'name': 'Glasgow', 'key': 'Port of Glasgow wikipedia', 'wiki': None} ,
{'name': 'Grangemouth', 'key': 'Port of Grangemouth wikipedia', 'wiki': None} ,
{'name': 'Hull', 'key': 'Port of Hull wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Hull'} ,
{'name': 'Leith', 'key': 'Port of Leith wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Leith_Harbour'} ,
{'name': 'Liverpool', 'key': 'Port of Liverpool wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Liverpool'} ,
{'name': 'London', 'key': 'Port of London wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_London'} ,
{'name': 'Manchester', 'key': 'Port of Manchester wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Manchester'} ,
{'name': 'Peterhead Bay', 'key': 'Port of Peterhead Bay wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Aberdeen_Harbour'} ,
{'name': 'Plymouth', 'key': 'Port of Plymouth wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Plymouth_Harbor'} ,
{'name': 'Portsmouth', 'key': 'Port of Portsmouth wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Portsmouth_International_Port'} ,
{'name': 'Scapa Flow', 'key': 'Port of Scapa Flow wikipedia', 'wiki': None} ,
{'name': 'Southampton', 'key': 'Port of Southampton wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Southampton'} ,
{'name': 'Sullom Voe', 'key': 'Port of Sullom Voe wikipedia', 'wiki': None} ,
{'name': 'Teesport', 'key': 'Port of Teesport wikipedia', 'wiki': None} ,
{'name': 'Thamesport', 'key': 'Port of Thamesport wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_London'} ,
{'name': 'Tyne', 'key': 'Port of Tyne wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tyne'} ,
{'name': 'Berdyansk', 'key': 'Port of Berdyansk wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Berdiansk'} ,
{'name': 'Kherson', 'key': 'Port of Kherson wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Kherson'} ,
{'name': 'Odessa', 'key': 'Port of Odessa wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Odessa'} ,
{'name': 'Reni', 'key': 'Port of Reni wikipedia', 'wiki': None} ,
{'name': 'Sevastopol', 'key': 'Port of Sevastopol wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Sevastopol'} ,
{'name': 'Ajman', 'key': 'Port of Ajman wikipedia', 'wiki': None} ,
{'name': 'Das Island', 'key': 'Port of Das Island wikipedia', 'wiki': None} ,
{'name': 'Dubai (Port Rashid)', 'key': 'Port of Dubai (Port Rashid) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Jebel_Ali'} ,
{'name': 'Fujairah', 'key': 'Port of Fujairah wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Fujairah'} ,
{'name': 'Jebel Dhanna/Ruwais', 'key': 'Port of Jebel Dhanna/Ruwais wikipedia', 'wiki': None} ,
{'name': 'Khor Fakkan', 'key': 'Port of Khor Fakkan wikipedia', 'wiki': None} ,
{'name': 'Mina Saqr', 'key': 'Port of Mina Saqr wikipedia', 'wiki': None} ,
{'name': 'Mina Zayed', 'key': 'Port of Mina Zayed wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Zayed_Port'} ,
{'name': 'Anacortes', 'key': 'Port of Anacortes wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Skagit_County'} ,
{'name': 'Ashtabula', 'key': 'Port of Ashtabula wikipedia', 'wiki': None} ,
{'name': 'Baltimore', 'key': 'Port of Baltimore wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Baltimore'} ,
{'name': 'Baton Rouge', 'key': 'Port of Baton Rouge wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Greater_Baton_Rouge'} ,
{'name': 'Beaumont', 'key': 'Port of Beaumont wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Beaumont'} ,
{'name': 'Boston', 'key': 'Port of Boston wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Boston'} ,
{'name': 'Charleston', 'key': 'Port of Charleston wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Charleston'} ,
{'name': 'Chicago', 'key': 'Port of Chicago wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Chicago'} ,
{'name': 'Cleveland', 'key': 'Port of Cleveland wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Cleveland'} ,
{'name': 'Corpus Christi', 'key': 'Port of Corpus Christi wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Corpus_Christi'} ,
{'name': 'Detroit', 'key': 'Port of Detroit wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Detroit'} ,
{'name': 'Duluth-Superior', 'key': 'Port of Duluth-Superior wikipedia', 'wiki': None} ,
{'name': 'Freeport', 'key': 'Port of Freeport wikipedia', 'wiki': None} ,
{'name': 'Hampton Roads', 'key': 'Port of Hampton Roads wikipedia', 'wiki': None} ,
{'name': 'Honolulu', 'key': 'Port of Honolulu wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Honolulu_Harbor'} ,
{'name': 'Houston', 'key': 'Port of Houston wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Houston'} ,
{'name': 'Huntington - Tri-State (WV)', 'key': 'Port of Huntington - Tri-State (WV) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Huntington_Tri-State'} ,
{'name': 'Jacksonville', 'key': 'Port of Jacksonville wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Jacksonville'} ,
{'name': 'Lake Charles', 'key': 'Port of Lake Charles wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Lake_Charles'} ,
{'name': 'Long Beach', 'key': 'Port of Long Beach wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Long_Beach'} ,
{'name': 'Los Angeles', 'key': 'Port of Los Angeles wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Los_Angeles'} ,
{'name': 'Manatee', 'key': 'Port of Manatee wikipedia', 'wiki': None} ,
{'name': 'Memphis', 'key': 'Port of Memphis wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Memphis'} ,
{'name': 'Miami', 'key': 'Port of Miami wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Miami_(album)'} ,
{'name': 'Mobile', 'key': 'Port of Mobile wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Mobile'} ,
{'name': 'New Orleans', 'key': 'Port of New Orleans wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_New_Orleans'} ,
{'name': 'New York/New Jersey', 'key': 'Port of New York/New Jersey wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_New_York_and_New_Jersey'} ,
{'name': 'Oakland', 'key': 'Port of Oakland wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Oakland'} ,
{'name': 'Pascagoula', 'key': 'Port of Pascagoula wikipedia', 'wiki': None} ,
{'name': 'Philadelphia', 'key': 'Port of Philadelphia wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Philadelphia'} ,
{'name': 'Pittsburgh', 'key': 'Port of Pittsburgh wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Pittsburgh'} ,
{'name': 'Plaquemines (Louisiana)', 'key': 'Port of Plaquemines (Louisiana) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Plaquemines_Port'} ,
{'name': 'Port Arthur', 'key': 'Port of Port Arthur wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Port_Arthur'} ,
{'name': 'Port Everglades', 'key': 'Port of Port Everglades wikipedia', 'wiki': None} ,
{'name': 'Portland (Maine)', 'key': 'Port of Portland (Maine) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Portland_(Maine)'} ,
{'name': 'Portland (Oregon)', 'key': 'Port of Portland (Oregon) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Portland_(Oregon)'} ,
{'name': 'Richmond (CA)', 'key': 'Port of Richmond (CA) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Richmond_(California)'} ,
{'name': 'Richmond (VA)', 'key': 'Port of Richmond (VA) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Richmond_(Virginia)'} ,
{'name': 'Savannah', 'key': 'Port of Savannah wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Savannah'} ,
{'name': 'Seattle', 'key': 'Port of Seattle wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Seattle'} ,
{'name': 'South Louisiana', 'key': 'Port of South Louisiana wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_South_Louisiana'} ,
{'name': 'Tacoma', 'key': 'Port of Tacoma wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Tacoma'} ,
{'name': 'Tampa', 'key': 'Port of Tampa wikipedia', 'wiki': None} ,
{'name': 'Texas City', 'key': 'Port of Texas City wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Texas_City'} ,
{'name': 'Valdez', 'key': 'Port of Valdez wikipedia', 'wiki': None} ,
{'name': 'Wilmington (DE)', 'key': 'Port of Wilmington (DE) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Wilmington_(Delaware)'} ,
{'name': 'Wilmington (NC)', 'key': 'Port of Wilmington (NC) wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Wilmington'} ,
{'name': 'Yakutat', 'key': 'Port of Yakutat wikipedia', 'wiki': None} ,
{'name': 'Fray Bentos', 'key': 'Port of Fray Bentos wikipedia', 'wiki': None} ,
{'name': 'Montevideo', 'key': 'Port of Montevideo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Montevideo'} ,
{'name': 'Nueva Palmira', 'key': 'Port of Nueva Palmira wikipedia', 'wiki': None} ,
{'name': 'Paysandu', 'key': 'Port of Paysandu wikipedia', 'wiki': None} ,
{'name': 'Port Vila', 'key': 'Port of Port Vila wikipedia', 'wiki': None} ,
{'name': 'Santo', 'key': 'Port of Santo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Port_of_Santos'} ,
{'name': 'Bajo Grande Refinery', 'key': 'Port of Bajo Grande Refinery wikipedia', 'wiki': None} ,
{'name': 'Cumana (Puerto Sucre)', 'key': 'Port of Cumana (Puerto Sucre) wikipedia', 'wiki': None} ,
{'name': 'La Guaira', 'key': 'Port of La Guaira wikipedia', 'wiki': None} ,
{'name': 'La Salina', 'key': 'Port of La Salina wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Salina'} ,
{'name': 'Maracaibo', 'key': 'Port of Maracaibo wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Miranda'} ,
{'name': 'Matanzas', 'key': 'Port of Matanzas wikipedia', 'wiki': None} ,
{'name': 'Palua', 'key': 'Port of Palua wikipedia', 'wiki': None} ,
{'name': 'Puerto Cabello', 'key': 'Port of Puerto Cabello wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_Cabello'} ,
{'name': 'Puerto La Cruz', 'key': 'Port of Puerto La Cruz wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Puerto_la_Cruz'} ,
{'name': 'Punta Cardon', 'key': 'Port of Punta Cardon wikipedia', 'wiki': None} ,
{'name': 'Danang', 'key': 'Port of Danang wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Da_Nang_Port'} ,
{'name': 'Haiphong', 'key': 'Port of Haiphong wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Hai_Phong_Port'} ,
{'name': 'Ho Chi Minh City', 'key': 'Port of Ho Chi Minh City wikipedia', 'wiki': 'https://en.wikipedia.org/wiki/Saigon_Port'} ,
{'name': 'Hon Gay', 'key': 'Port of Hon Gay wikipedia', 'wiki': None} ,
{'name': 'Nha Trang', 'key': 'Port of Nha Trang wikipedia', 'wiki': None} ,
{'name': 'Charlotte Amalie,St. Thomas', 'key': 'Port of Charlotte Amalie,St. Thomas wikipedia', 'wiki': None} ,
{'name': 'Christiansted, St. Croix', 'key': 'Port of Christiansted, St. Croix wikipedia', 'wiki': None} ,
{'name': 'Limetree Bay', 'key': 'Port of Limetree Bay wikipedia', 'wiki': None} ,
{'name': 'Aden', 'key': 'Port of Aden wikipedia', 'wiki': None} ,
{'name': 'Hodeidah', 'key': 'Port of Hodeidah wikipedia', 'wiki': None} ,
{'name': 'Mokha', 'key': 'Port of Mokha wikipedia', 'wiki': None} ,
{'name': 'Mukalla', 'key': 'Port of Mukalla wikipedia', 'wiki': None}
]
